### ISSUE TITLE
Консистентность

### ISSUE THREAD

**Issue by coursar** [philosovCo/autocatalog#11]
https://github.com/philosovCo/autocatalog/blob/2a5d73b16d457cd86bec998fa7ba0060f9481e19/src/main/java/ru/itpark/query/AutoQuery.java#L25-L43

Смысл был городить "крутую логику" с рефлексией, если ниже при `CREATE TABLE` вы руками захардкодили все поля?

Тогда уж и там нужно собрать через Reflection.

**Comment by ruslan-nizamov** [comment]
сделал через Reflection
 e00938e6f50b117546c9e03d4d1d9b0d20e93932
