### ISSUE TITLE
Зачем нужен этот метод?

### ISSUE THREAD

**Issue by coursar** [philosovCo/autocatalog#15]
https://github.com/philosovCo/autocatalog/blob/2a5d73b16d457cd86bec998fa7ba0060f9481e19/src/main/java/ru/itpark/service/ImageService.java#L51-L71

**Comment by ruslan-nizamov** [comment]
Это реализация проверки ссылки и файла на наличие на хосте, если пройдет по условию то из csv идентификатор картинки (из ссылки) проставлялся для записи бд, делал на локале без сброса ресурсов. согласен, бесполезная реализация, просто эксперементировал

**Comment by coursar** [comment]
Здесь нужно учитывать следующую вещь: если загружать будут файл из нескольких тысяч записей, вы можете на каждую потратить время. Поэтому для этого мы будем рассматривать альтернативные инструменты.

Задача специально поставлена так, чтобы вы об этом задумались.
