### ISSUE TITLE
Нажимаешь на Import, выходит - Removal

### ISSUE THREAD

**Issue by coursar** [philosovCo/autocatalog#3]
![Screenshot from 2019-05-08 19-02-14](https://user-images.githubusercontent.com/3601892/57389955-ecfbd800-71c3-11e9-9815-583ed97cd85a.png)

**Comment by ruslan-nizamov** [comment]
исправлено
ea52f3c99a39978a5f97cc84a446b5ee9711bea1

**Comment by coursar** [comment]
Если исправлено, то: закрывайте issue сообщением коммита, т.е. прямо в сообщении коммита пишете "fixes #3"
