### ISSUE TITLE
Template называют класс, который инкапсулирует повторяющуюся логику и не привязан к бизнес-сущностям

### ISSUE THREAD

**Issue by coursar** [philosovCo/autocatalog#9]
https://github.com/philosovCo/autocatalog/blob/2a5d73b16d457cd86bec998fa7ba0060f9481e19/src/main/java/ru/itpark/template/DBTemplate.java#L35-L64

У вас же идёт завязка на Auto, хотя в названии класса и метода про Auto ни слова

**Comment by coursar** [comment]
Всё равно Auto осталось

**Comment by ruslan-nizamov** [comment]
я вернул в AutoService. он относится к Auto, поэтому я не стал делать универсальным для других сущностей

**Comment by coursar** [comment]
Ок
